### ISSUE TITLE
[BUG] Blured imagen and videos in ver. 1.6.0

### ISSUE THREAD

**Issue by edilberto507h** [TwidereProject/TwidereX-Android#467] opened 2022-07-19 21:44 UTC
In version 1.6.0, when browsing the time line the vídeos and some photos are blured.

**To Reproduce**
1)Open the app
2)Refresh time line
3)Browse the twittes shown some al blured
Click on photos, the twitte shows with the photo looking ok, but if its a vídeo it is blured and dont play.

**Expected behavior**
By my default settings it should act like in ver. 1.5.1 vídeos 
Should play and pictures look without blur in preview

**Smartphone (please complete the following information):**
 - Device: LG K42
 - OS: Android 11
 - Variant Google Play, FDroid
 - Version 1.6.0 failed, 
 - version 1.5.1 OK
![pixlr_20220720162612658](https://user-images.githubusercontent.com/109629876/180085450-5ab19dff-fa1a-4744-9c1c-d6ee793e81c4.jpg)

**Comment by edilberto507h** [comment] 2022-07-20 21:31
Added photos

**Comment by enaix** [comment] 2022-07-21 10:50
This is not a bug, since these tweets are marked as sensitive (the blur feature was introduced in 1.6.0)

**Comment by edilberto507h** [comment] 2022-07-21 15:55
> This is not a bug, since these tweets are marked as sensitive (the blur feature was introduced in 1.6.0)

Thanks for the answer, but first how do that function could be disabled, changed my account sensitive content preview to show, but twidere-x keep bluring the videos and photos.
In the time line, and when checking the twitts section of the account that its content is blured, i noticed that the videos wont play, but in the photo & vídeo, there is no blur, and all videos play fine.

**Comment by Tlaster** [comment] 2022-07-22 05:24
> > This is not a bug, since these tweets are marked as sensitive (the blur feature was introduced in 1.6.0)
> 
> Thanks for the answer, but first how do that function could be disabled, changed my account sensitive content preview to show, but twidere-x keep bluring the videos and photos. In the time line, and when checking the twitts section of the account that its content is blured, i noticed that the videos wont play, but in the photo & vídeo, there is no blur, and all videos play fine.

We're considering adding an option to disable the blur effect for sensitive content.

**Comment by Enovale** [comment] 2022-07-24 05:04
Considering? Why was this feature even implemented if it isn't going to be configurable? It's ridiculous to force this on users, especially in an open app like this. I could understand if this was a bug or part of a beta and it wasn't implemented, but instead you're *considering* it?

Please, consider making this configurable.

**Comment by Tlaster** [comment] 2022-07-24 10:18
> Considering? Why was this feature even implemented if it isn't going to be configurable? It's ridiculous to force this on users, especially in an open app like this. I could understand if this was a bug or part of a beta and it wasn't implemented, but instead you're _considering_ it?
 
We're short of developers right now and we still have lots of things to be done,  so it's _considering_ rather that _doing_ it, we do want this to be configurable.

**Comment by xlucn** [comment] 2022-10-18 03:09
Could you revert the code adding this "feature" (hopefully before 1.7.0), and add it back after implementing a switch?

**Comment by Tlaster** [comment] 2023-02-01 04:57
Now there is a toggle after 1.7.0-beta01.

**Closed as completed by Tlaster** 2023-02-01 04:57 UTC
Labels: bug
