### ISSUE TITLE
[BUG] another video playing on top of current one

### ISSUE THREAD

**Issue by OliverLew** [TwidereProject/TwidereX-Android#236] opened 2021-07-30 06:51 UTC
**Describe the bug**
When the current video is playing, sometimes the video in the second (that's what I always see) tweet below will play inside the current video area, for detailed behavior, see the screen recording below.

**To Reproduce**
1. Probably should enable video autoplay
2. Go to a list of tweets with videos
3. Scroll down to trigger video autoplay

**Expected behavior**
Only the current video playing

**Screenshots**

https://user-images.githubusercontent.com/12032219/127612226-30ee83bf-6ad2-43b7-8c67-1b002919ab7a.mp4

**Smartphone (please complete the following information):**
 - Device: Oneplus 8
 - OS: Lineage OS 18.1, Android 11
 - Variant: F-droid
 - Version: 1.4.0

**Additional context**

I have tried clearing all app data and reinstalling twidere.

**Comment by OliverLew** [comment] 2021-08-30 15:06
I don't see this in 1.5.0 anymore. Is it possible that it is fixed somehow?

**Comment by Tlaster** [comment] 2021-08-31 08:36
oops, duplicate of #81 which was fixed in 1.3.0

**Closed by Tlaster** 2021-08-31 08:36 UTC
Labels: bug

**Comment by OliverLew** [comment] 2021-08-31 08:48
@Tlaster I wonder if it's the same issue. But if it is really fixed, that doesn't matter anyway. :)

#81 shows a smaller preview of the current video when playing full-screen.
In my issue, I saw another video playing above the current one (in a fixed position).

I had #81 before. After upgrading to 1.4.0, I don't have #81 but this issue appears. In 1.5.0, this issue disappeared (on my phone).
